// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiserviciosPiscinas.Models;

#nullable disable

namespace MultiserviciosPiscinas.Migrations
{
    [DbContext(typeof(PiscinasYMultiserviciosContext))]
    [Migration("20260706200837_CrearTablaNotificacion")]
    partial class CrearTablaNotificacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("autor_id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateOnly?>("FechaCaducidad")
                        .HasColumnType("date")
                        .HasColumnName("fecha_caducidad");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("prioridad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PK__ANUNCIO__3213E83FBE07E040");

                    b.HasIndex("AutorId");

                    b.ToTable("ANUNCIO", "crm");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.BitacoraAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tabla_afectada");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id")
                        .HasName("PK__BITACORA__3213E83FD494B8F9");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BITACORA_AUDITORIA", "aud");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Canton", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int")
                        .HasColumnName("provincia_id");

                    b.HasKey("Id")
                        .HasName("PK__CANTON__3213E83FDD32ABCB");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("CANTON", "geo");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en");

                    b.HasKey("Id")
                        .HasName("PK__CARRITO__3213E83F5EE198E8");

                    b.HasIndex("ClienteId");

                    b.ToTable("CARRITO", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.CategoriaGastoOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("Id")
                        .HasName("PK__CATEGORI__3213E83FF9237933");

                    b.ToTable("CATEGORIA_GASTO_OPERATIVO", "fin");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("Id")
                        .HasName("PK__CATEGORI__3213E83FECBD5E09");

                    b.ToTable("CATEGORIA_PRODUCTO", "inv");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notas");

                    b.Property<int>("PiscinaId")
                        .HasColumnType("int")
                        .HasColumnName("piscina_id");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int")
                        .HasColumnName("tecnico_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("PK__CITA__3213E83F7BE5BB6B");

                    b.HasIndex("PiscinaId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("CITA", "ops");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__CLIENTE__3213E83F640B272D");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ_CLIENTE_USUARIO")
                        .IsUnique();

                    b.ToTable("CLIENTE", "cli");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("DescuentoTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("descuento_total");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateOnly>("FechaVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vigencia");

                    b.Property<decimal>("ImpuestoTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("impuesto_total");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__COTIZACI__3213E83F4F02A015");

                    b.HasIndex("ClienteId");

                    b.ToTable("COTIZACION", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DetalleCotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadPropuesta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad_propuesta");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int")
                        .HasColumnName("cotizacion_id");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("descuento");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("impuesto");

                    b.Property<decimal>("LineaSubtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("linea_subtotal");

                    b.Property<decimal>("LineaTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("linea_total");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("PK__DETALLE___3213E83FCDA15464");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DETALLE_COTIZACION", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadVendida")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad_vendida");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("descuento");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("impuesto");

                    b.Property<decimal>("LineaSubtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("linea_subtotal");

                    b.Property<decimal>("LineaTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("linea_total");

                    b.Property<decimal>("PrecioUnitarioFinal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario_final");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("PK__DETALLE___3213E83FFCF81901");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DETALLE_FACTURA", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DireccionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("CodigoPostal")
                        .HasColumnType("int")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("detalles");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int")
                        .HasColumnName("distrito_id");

                    b.Property<byte>("EsPrincipal")
                        .HasColumnType("tinyint")
                        .HasColumnName("es_principal");

                    b.Property<string>("TipoDireccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_direccion");

                    b.HasKey("Id")
                        .HasName("PK__DIRECCIO__3213E83F2969199A");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DistritoId");

                    b.ToTable("DIRECCION_CLIENTE", "cli");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CantonId")
                        .HasColumnType("int")
                        .HasColumnName("canton_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__DISTRITO__3213E83F29F5819C");

                    b.HasIndex("CantonId");

                    b.ToTable("DISTRITO", "geo");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_envio");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("PK__ENCUESTA__3213E83F919BD247");

                    b.HasIndex(new[] { "ServicioId" }, "UQ_ENCUESTA_SERVICIO")
                        .IsUnique();

                    b.ToTable("ENCUESTA", "crm");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Equipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__EQUIPAMI__3213E83FDFCF68FA");

                    b.ToTable("EQUIPAMIENTO", "act");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ComprobanteSinpeRuta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comprobante_sinpe_ruta");

                    b.Property<string>("CondicionPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("condicion_pago");

                    b.Property<int?>("CotizacionId")
                        .HasColumnType("int")
                        .HasColumnName("cotizacion_id");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<decimal>("DescuentoTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("descuento_total");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal>("ImpuestoTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("impuesto_total");

                    b.Property<string>("NumeroConsecutivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_consecutivo");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__FACTURA__3213E83F610193A4");

                    b.HasIndex("ClienteId");

                    b.HasIndex(new[] { "NumeroConsecutivo" }, "UQ_FACTURA_CONSECUTIVO")
                        .IsUnique();

                    b.HasIndex(new[] { "CotizacionId" }, "UQ_FACTURA_COTIZACION")
                        .IsUnique()
                        .HasFilter("[cotizacion_id] IS NOT NULL");

                    b.ToTable("FACTURA", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.GastoOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<string>("ComprobanteRuta")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comprobante_ruta");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("motivo_rechazo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__GASTO_OP__3213E83F2091F899");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GASTO_OPERATIVO", "fin");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AcidoCianurico")
                        .HasColumnType("float")
                        .HasColumnName("acido_cianurico");

                    b.Property<double?>("Alcalinidad")
                        .HasColumnType("float")
                        .HasColumnName("alcalinidad");

                    b.Property<double?>("Calcio")
                        .HasColumnType("float")
                        .HasColumnName("calcio");

                    b.Property<double?>("CloroPpm")
                        .HasColumnType("float")
                        .HasColumnName("cloro_ppm");

                    b.Property<DateOnly>("FechaInspeccion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inspeccion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<double?>("Ph")
                        .HasColumnType("float")
                        .HasColumnName("ph");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.Property<double?>("TemperaturaC")
                        .HasColumnType("float")
                        .HasColumnName("temperatura_c");

                    b.HasKey("Id")
                        .HasName("PK__INSPECCI__3213E83FC74FC454");

                    b.HasIndex("ServicioId");

                    b.ToTable("INSPECCION", "ops");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.ItemCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int")
                        .HasColumnName("carrito_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("PK__ITEM_CAR__3213E83FCF5D1505");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ITEM_CARRITO", "ven");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("mensaje");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NOTIFICACION", "ops");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Piscina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int")
                        .HasColumnName("direccion_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<double>("VolumenM3")
                        .HasColumnType("float")
                        .HasColumnName("volumen_m3");

                    b.HasKey("Id")
                        .HasName("PK__PISCINA__3213E83FEB3F804C");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DireccionId");

                    b.ToTable("PISCINA", "act");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.PiscinaEquipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipamientoId")
                        .HasColumnType("int")
                        .HasColumnName("equipamiento_id");

                    b.Property<int>("PiscinaId")
                        .HasColumnType("int")
                        .HasColumnName("piscina_id");

                    b.HasKey("Id")
                        .HasName("PK__PISCINA___3213E83F7FD15167");

                    b.HasIndex("EquipamientoId");

                    b.HasIndex(new[] { "PiscinaId", "EquipamientoId" }, "UQ_PISCINA_EQUIPAMIENTO")
                        .IsUnique();

                    b.ToTable("PISCINA_EQUIPAMIENTO", "act");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCTO__3213E83FED7556DA");

                    b.HasIndex("CategoriaId");

                    b.ToTable("PRODUCTO", "inv");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__PROVINCI__3213E83F0AE981CD");

                    b.ToTable("PROVINCIA", "geo");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.ProyectoConstruccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFinEstimada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_estimada");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PiscinaId")
                        .HasColumnType("int")
                        .HasColumnName("piscina_id");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("presupuesto");

                    b.HasKey("Id")
                        .HasName("PK__PROYECTO__3213E83FF1B37E32");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PiscinaId");

                    b.ToTable("PROYECTO_CONSTRUCCION", "pry");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__ROL__3213E83FDA44A0DB");

                    b.ToTable("ROL", "seg");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.RutaOptimizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DistanciaTotalKm")
                        .HasColumnType("float")
                        .HasColumnName("distancia_total_km");

                    b.Property<int?>("DuracionTotalMin")
                        .HasColumnType("int")
                        .HasColumnName("duracion_total_min");

                    b.Property<string>("EnlaceGoogleMaps")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("enlace_google_maps");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("GeneradaEn")
                        .HasColumnType("datetime")
                        .HasColumnName("generada_en");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int")
                        .HasColumnName("tecnico_id");

                    b.HasKey("Id")
                        .HasName("PK__RUTA_OPT__3213E83FEFBA2F6B");

                    b.HasIndex("TecnicoId");

                    b.ToTable("RUTA_OPTIMIZADA", "log");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cierre");

                    b.Property<string>("TrabajoRealizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trabajo_realizado");

                    b.HasKey("Id")
                        .HasName("PK__SERVICIO__3213E83FDA07485A");

                    b.HasIndex(new[] { "CitaId" }, "UQ_SERVICIO_CITA")
                        .IsUnique();

                    b.ToTable("SERVICIO", "ops");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.TareaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaAsignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateOnly?>("FechaCompletacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_completacion");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("PK__TAREA_SE__3213E83F9CCE3DAC");

                    b.HasIndex("ServicioId");

                    b.ToTable("TAREA_SERVICIO", "ops");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.TelefonosCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<byte>("EsPrincipal")
                        .HasColumnType("tinyint")
                        .HasColumnName("es_principal");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_telefono");

                    b.Property<string>("TipoTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_telefono");

                    b.HasKey("Id")
                        .HasName("PK__TELEFONO__3213E83F071450C8");

                    b.HasIndex("ClienteId");

                    b.ToTable("TELEFONOS_CLIENTE", "cli");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("PK__USUARIO__3213E83F34D090B6");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Correo" }, "UQ_USUARIO_CORREO")
                        .IsUnique();

                    b.ToTable("USUARIO", "seg");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("placa");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int")
                        .HasColumnName("tecnico_id");

                    b.HasKey("Id")
                        .HasName("PK__VEHICULO__3213E83FDE195E87");

                    b.HasIndex("TecnicoId");

                    b.HasIndex(new[] { "Placa" }, "UQ_VEHICULO_PLACA")
                        .IsUnique();

                    b.ToTable("VEHICULO", "log");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.VisitaRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<double?>("DistanciaTramoKm")
                        .HasColumnType("float")
                        .HasColumnName("distancia_tramo_km");

                    b.Property<int?>("DuracionTramoMin")
                        .HasColumnType("int")
                        .HasColumnName("duracion_tramo_min");

                    b.Property<int>("OrdenVisita")
                        .HasColumnType("int")
                        .HasColumnName("orden_visita");

                    b.Property<int>("RutaId")
                        .HasColumnType("int")
                        .HasColumnName("ruta_id");

                    b.HasKey("Id")
                        .HasName("PK__VISITA_R__3213E83FF1F8B4BF");

                    b.HasIndex("RutaId");

                    b.HasIndex(new[] { "CitaId" }, "UQ_VISITA_RUTA_CITA")
                        .IsUnique();

                    b.ToTable("VISITA_RUTA", "log");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Anuncio", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Autor")
                        .WithMany("Anuncio")
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK_ANUNCIO_AUTOR");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.BitacoraAuditoria", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Usuario")
                        .WithMany("BitacoraAuditoria")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_BITACORA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Canton", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Provincia", "Provincia")
                        .WithMany("Canton")
                        .HasForeignKey("ProvinciaId")
                        .IsRequired()
                        .HasConstraintName("FK_CANTON_PROVINCIA");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Carrito", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("Carrito")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_CARRITO_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cita", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Piscina", "Piscina")
                        .WithMany("Cita")
                        .HasForeignKey("PiscinaId")
                        .IsRequired()
                        .HasConstraintName("FK_CITA_PISCINA");

                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Tecnico")
                        .WithMany("Cita")
                        .HasForeignKey("TecnicoId")
                        .IsRequired()
                        .HasConstraintName("FK_CITA_TECNICO");

                    b.Navigation("Piscina");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cliente", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("MultiserviciosPiscinas.Models.Cliente", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_CLIENTE_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cotizacion", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("Cotizacion")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_COTIZACION_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DetalleCotizacion", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cotizacion", "Cotizacion")
                        .WithMany("DetalleCotizacion")
                        .HasForeignKey("CotizacionId")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLE_COT_COTIZACION");

                    b.HasOne("MultiserviciosPiscinas.Models.Producto", "Producto")
                        .WithMany("DetalleCotizacion")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLE_COT_PRODUCTO");

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DetalleFactura", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Factura", "Factura")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("FacturaId")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLE_FAC_FACTURA");

                    b.HasOne("MultiserviciosPiscinas.Models.Producto", "Producto")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLE_FAC_PRODUCTO");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DireccionCliente", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("DireccionCliente")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_DIRECCION_CLIENTE_CLIENTE");

                    b.HasOne("MultiserviciosPiscinas.Models.Distrito", "Distrito")
                        .WithMany("DireccionCliente")
                        .HasForeignKey("DistritoId")
                        .IsRequired()
                        .HasConstraintName("FK_DIRECCION_CLIENTE_DISTRITO");

                    b.Navigation("Cliente");

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Distrito", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Canton", "Canton")
                        .WithMany("Distrito")
                        .HasForeignKey("CantonId")
                        .IsRequired()
                        .HasConstraintName("FK_DISTRITO_CANTON");

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Encuesta", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Servicio", "Servicio")
                        .WithOne("Encuesta")
                        .HasForeignKey("MultiserviciosPiscinas.Models.Encuesta", "ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_ENCUESTA_SERVICIO");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Factura", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("Factura")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_FACTURA_CLIENTE");

                    b.HasOne("MultiserviciosPiscinas.Models.Cotizacion", "Cotizacion")
                        .WithOne("Factura")
                        .HasForeignKey("MultiserviciosPiscinas.Models.Factura", "CotizacionId")
                        .HasConstraintName("FK_FACTURA_COTIZACION");

                    b.Navigation("Cliente");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.GastoOperativo", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.CategoriaGastoOperativo", "Categoria")
                        .WithMany("GastoOperativo")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_GASTO_CATEGORIA");

                    b.HasOne("MultiserviciosPiscinas.Models.Cita", "Cita")
                        .WithMany("GastoOperativo")
                        .HasForeignKey("CitaId")
                        .HasConstraintName("FK_GASTO_CITA");

                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Usuario")
                        .WithMany("GastoOperativo")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_GASTO_USUARIO");

                    b.Navigation("Categoria");

                    b.Navigation("Cita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Inspeccion", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Servicio", "Servicio")
                        .WithMany("Inspeccion")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_INSPECCION_SERVICIO");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.ItemCarrito", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Carrito", "Carrito")
                        .WithMany("ItemCarrito")
                        .HasForeignKey("CarritoId")
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_CARRITO");

                    b.HasOne("MultiserviciosPiscinas.Models.Producto", "Producto")
                        .WithMany("ItemCarrito")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_PRODUCTO");

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Notificacion", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cita", "Cita")
                        .WithMany("Notificacion")
                        .HasForeignKey("CitaId")
                        .HasConstraintName("FK_NOTIFICACION_CITA");

                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Usuario")
                        .WithMany("Notificacion")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICACION_USUARIO");

                    b.Navigation("Cita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Piscina", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("Piscina")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_PISCINA_CLIENTE");

                    b.HasOne("MultiserviciosPiscinas.Models.DireccionCliente", "Direccion")
                        .WithMany("Piscina")
                        .HasForeignKey("DireccionId")
                        .IsRequired()
                        .HasConstraintName("FK_PISCINA_DIRECCION");

                    b.Navigation("Cliente");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.PiscinaEquipamiento", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Equipamiento", "Equipamiento")
                        .WithMany("PiscinaEquipamiento")
                        .HasForeignKey("EquipamientoId")
                        .IsRequired()
                        .HasConstraintName("FK_PE_EQUIPAMIENTO");

                    b.HasOne("MultiserviciosPiscinas.Models.Piscina", "Piscina")
                        .WithMany("PiscinaEquipamiento")
                        .HasForeignKey("PiscinaId")
                        .IsRequired()
                        .HasConstraintName("FK_PE_PISCINA");

                    b.Navigation("Equipamiento");

                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Producto", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.CategoriaProducto", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTO_CATEGORIA");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.ProyectoConstruccion", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("ProyectoConstruccion")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_PROYECTO_CLIENTE");

                    b.HasOne("MultiserviciosPiscinas.Models.Piscina", "Piscina")
                        .WithMany("ProyectoConstruccion")
                        .HasForeignKey("PiscinaId")
                        .HasConstraintName("FK_PROYECTO_PISCINA");

                    b.Navigation("Cliente");

                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.RutaOptimizada", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Tecnico")
                        .WithMany("RutaOptimizada")
                        .HasForeignKey("TecnicoId")
                        .IsRequired()
                        .HasConstraintName("FK_RUTA_TECNICO");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Servicio", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cita", "Cita")
                        .WithOne("Servicio")
                        .HasForeignKey("MultiserviciosPiscinas.Models.Servicio", "CitaId")
                        .IsRequired()
                        .HasConstraintName("FK_SERVICIO_CITA");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.TareaServicio", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Servicio", "Servicio")
                        .WithMany("TareaServicio")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_TAREA_SERVICIO");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.TelefonosCliente", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cliente", "Cliente")
                        .WithMany("TelefonosCliente")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_TELEFONOS_CLIENTE_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Usuario", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Rol", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_ROL");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Vehiculo", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Usuario", "Tecnico")
                        .WithMany("Vehiculo")
                        .HasForeignKey("TecnicoId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICULO_TECNICO");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.VisitaRuta", b =>
                {
                    b.HasOne("MultiserviciosPiscinas.Models.Cita", "Cita")
                        .WithOne("VisitaRuta")
                        .HasForeignKey("MultiserviciosPiscinas.Models.VisitaRuta", "CitaId")
                        .IsRequired()
                        .HasConstraintName("FK_VISITA_CITA");

                    b.HasOne("MultiserviciosPiscinas.Models.RutaOptimizada", "Ruta")
                        .WithMany("VisitaRuta")
                        .HasForeignKey("RutaId")
                        .IsRequired()
                        .HasConstraintName("FK_VISITA_RUTA");

                    b.Navigation("Cita");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Canton", b =>
                {
                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Carrito", b =>
                {
                    b.Navigation("ItemCarrito");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.CategoriaGastoOperativo", b =>
                {
                    b.Navigation("GastoOperativo");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cita", b =>
                {
                    b.Navigation("GastoOperativo");

                    b.Navigation("Notificacion");

                    b.Navigation("Servicio");

                    b.Navigation("VisitaRuta");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cliente", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Cotizacion");

                    b.Navigation("DireccionCliente");

                    b.Navigation("Factura");

                    b.Navigation("Piscina");

                    b.Navigation("ProyectoConstruccion");

                    b.Navigation("TelefonosCliente");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Cotizacion", b =>
                {
                    b.Navigation("DetalleCotizacion");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.DireccionCliente", b =>
                {
                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Distrito", b =>
                {
                    b.Navigation("DireccionCliente");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Equipamiento", b =>
                {
                    b.Navigation("PiscinaEquipamiento");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Factura", b =>
                {
                    b.Navigation("DetalleFactura");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Piscina", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("PiscinaEquipamiento");

                    b.Navigation("ProyectoConstruccion");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Producto", b =>
                {
                    b.Navigation("DetalleCotizacion");

                    b.Navigation("DetalleFactura");

                    b.Navigation("ItemCarrito");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Provincia", b =>
                {
                    b.Navigation("Canton");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.RutaOptimizada", b =>
                {
                    b.Navigation("VisitaRuta");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Servicio", b =>
                {
                    b.Navigation("Encuesta");

                    b.Navigation("Inspeccion");

                    b.Navigation("TareaServicio");
                });

            modelBuilder.Entity("MultiserviciosPiscinas.Models.Usuario", b =>
                {
                    b.Navigation("Anuncio");

                    b.Navigation("BitacoraAuditoria");

                    b.Navigation("Cita");

                    b.Navigation("Cliente");

                    b.Navigation("GastoOperativo");

                    b.Navigation("Notificacion");

                    b.Navigation("RutaOptimizada");

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
